echo "If you are having problems with running this script do \"su postgres\" and try again"

psql -c "create database tuktuk;"
psql -c "create user tuk with encrypted password ZuppaSecurePwd;"
psql -c "GRANT ALL PRIVILEGES ON DATABASE tuktuk TO tuk;"
psql -c "ALTER USER tuk WITH SUPERUSER;"
psql -U tuk -d tuktuk -c "create table http(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table ftp(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table https(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table tcp(id serial, data varchar, source_ip varchar, time varchar, port int);"
psql -U tuk -d tuktuk -c "create table ldap(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table smtp(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table smb(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table dns(id serial, data varchar, source_ip varchar, time varchar);"
psql -U tuk -d tuktuk -c "create table dns_domains(id serial, domain varchar unique, delete_time bigint);"

echo "[*] If you have received no errors during database init everything is fine"
echo "Now you will have to set up https certificates for your domain"
